services: 
  clickhouse:
    image: clickhouse/clickhouse-server:26.3-alpine
    container_name: attribution_clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      CLICKHOUSE_MAX_SERVER_MEMORY_USAGE: "1073741824"
    volumes: 
      - clickhouse_data:/var/lib/clickhouse

volumes:
  clickhouse_data:
