[package]
name = "attribution-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8"
tokio = {version = "1.0", features = ["full"]}
redis = "1.6.0"
deadpool-redis = "0.23.1"
testcontainers-modules = {version = "0.15.0", features = ["postgres", "redis", "blocking"]}
uuid = { version = "1.26.0", features = ["v7"]}
sqlx = { version = "0.9", features = [ "runtime-tokio", "postgres" ] }
